#/pbs/software/centos-8-x86_64/cmake/3.25.3/bin/cmake -H. -B build/nvcc -DCMAKE_CXX_COMPILER=nvcc -DCMAKE_PREFIX_PATH="${PY_PATHS}" -DUSE_CUDA=ON -DCMAKE_PREFIX_PATH="/pbs/software/centos-8-x86_64/boost/1.84.0/lib/cmake/boost_python-1.84.0" # -DCMAKE_CUDA_ARCHITECTURES=native
#cmake -H. -B build/nvcc -DCMAKE_CXX_COMPILER=nvcc -DCXX_SUPPORTS_FPIC=true -DCMAKE_CUDA_FLAGS="-allow-unsupported-compiler" -D CUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-12 -DCMAKE_PREFIX_PATH="${PY_PATHS}" -DUSE_CUDA=ON # -DCMAKE_CUDA_ARCHITECTURES=native
#cmake --build build/nvcc --
#cmake -H. -B build/nvcc -DCMAKE_CXX_COMPILER=nvcc -DCMAKE_PREFIX_PATH="/pbs/software/centos-8-x86_64/boost/1.84.0/lib/cmake/Boost-1.84.0;/pbs/software/centos-8-x86_64/boost/1.84.0/lib/cmake/boost_filesystem-1.84.0;/pbs/software/centos-8-x86_64/root/6.28.12/share/root/cmake;/pbs/software/centos-8-x86_64/root/6.28.12/lib;/pbs/software/centos-8-x86_64/root/6.28.12/include/root;" -DCMAKE_CUDA_ARCHITECTURES=native
#cmake -H. -B build/nvcc -DCMAKE_CXX_COMPILER=nvcc -DCXX_SUPPORTS_FPIC=true -DCMAKE_PREFIX_PATH="/pbs/software/centos-8-x86_64/boost/1.84.0-p/lib/cmake/Boost-1.84.0;/pbs/software/centos-8-x86_64/root/6.28.12/share/root/cmake;/pbs/software/centos-8-x86_64/root/6.28.12/lib;/pbs/software/centos-8-x86_64/root/6.28.12/include/root;/sps/l2it/collard/anaconda3/lib/python3.11/site-packages/torch/include/torch/csrc/api/include;/sps/l2it/collard/anaconda3/lib/python3.11/site-packages/torch/share/cmake/Torch;/sps/l2it/collard/anaconda3/lib/python3.11/site-packages/torch/include;/sps/l2it/collard/anaconda3/lib/python3.11/site-packages/torch/include;" # -DCMAKE_CUDA_ARCHITECTURES=native
#cmake --build build/nvcc --
#cmake --build build/nvcc -- -j 4
#nvcc -O3 -c device.cu
#nvcc -std=c++17 -O3 -c host.cpp
#nvcc -o tester device.o host.o
BIN=build/nvcc/bin
mkdir $BIN
Tracking_path=/global/homes/j/jamesgab/ModuleMapGraph/
#nvcc -std=c++11 -o ${BIN}/memoryscheduler.o -c ${PWD}/GPU/src/memoryscheduler.cu -DTHRUST_IGNORE_DEPRECATED_CPP_DIALECT -DCUB_IGNORE_DEPRECATED_CPP_DIALECT
#nvcc -std=c++11 -o ${BIN}/datatypes.o -c ${PWD}/GPU/src/datatypes.cu -DTHRUST_IGNORE_DEPRECATED_CPP_DIALECT -DCUB_IGNORE_DEPRECATED_CPP_DIALECT
#nvcc -std=c++11 -o ${BIN}/triplet_finder.o -c ${PWD}/GPU/src/triplet_finder.cu -DTHRUST_IGNORE_DEPRECATED_CPP_DIALECT -DCUB_IGNORE_DEPRECATED_CPP_DIALECT
#nvcc -g -G -std=c++11 -o ${BIN}/utility.o -c ${PWD}/GPU/src/utility.cu -DTHRUST_IGNORE_DEPRECATED_CPP_DIALECT -DCUB_IGNORE_DEPRECATED_CPP_DIALECT
#nvcc -std=c++11 -o ${BIN}/main.o -c ${PWD}/GPU/utils/main.cu -DTHRUST_IGNORE_DEPRECATED_CPP_DIALECT -DCUB_IGNORE_DEPRECATED_CPP_DIALECT
#nvcc -o ${BIN}/main ${BIN}/triplet_finder.o ${BIN}/datatypes.o ${BIN}/memoryscheduler.o ${BIN}/utility.o ${BIN}/main.o -DTHRUST_IGNORE_DEPRECATED_CPP_DIALECT -DCUB_IGNOR

nvcc -std=c++17 -lstdc++fs -O3 -allow-unsupported-compiler -I /usr/include/boost/ -I ${Tracking_path}/headers -I ${Tracking_path}/include -I ${Tracking_path}/src -I ${Tracking_path}/CPU/headers -I ${Tracking_path}/CPU/include -I ${Tracking_path}/CPU/src -I ${Tracking_path}/GPU/headers -I ${Tracking_path}/GPU/include -I ${Tracking_path}/GPU/src -I /usr/local/root/include/ -o ${BIN}/GraphBuilder.exe ${PWD}/GPU/utils/GraphBuilder.cu -L /usr/lib/x86_64-linux-gnu -lboost_regex -lboost_iostreams -lboost_program_options -L /usr/local/root/lib -lCore -lTree -lRIO -I /opt/conda/envs/gnn4itk/include/python3.10 -I /opt/conda/envs/gnn4itk/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I /opt/conda/envs/gnn4itk/lib/python3.10/site-packages/torch/include -L /opt/conda/envs/gnn4itk/lib $(python3.10-config --ldflags --embed)
nvcc -std=c++17 -lstdc++fs -O3 -allow-unsupported-compiler -I /usr/include/boost/ -I /pbs/software/centos-8-x86_64/boost/1.84.0/include -I ${Tracking_path}/headers -I ${Tracking_path}/include -I ${Tracking_path}/src -I ${Tracking_path}/CPU/headers -I ${Tracking_path}/CPU/include -I ${Tracking_path}/CPU/src -I ${Tracking_path}/GPU/headers -I ${Tracking_path}/GPU/include -I ${Tracking_path}/GPU/src -I /pbs/software/centos-8-x86_64/root/6.28.12/include/root/ -I /usr/local/root/include/ -o ${BIN}/WalkThrough.exe ${PWD}/GPU/utils/WalkThrough.cu -L /pbs/software/centos-8-x86_64/boost/1.84.0/lib  -lboost_regex -lboost_iostreams -lboost_program_options -L /pbs/software/centos-8-x86_64/root/6.28.12/lib -L /usr/local/root/lib -lCore -lTree -lRIO -I /sps/l2it/collard/anaconda3/include/python3.11 -I /sps/l2it/collard/anaconda3/lib/python3.11/site-packages/torch/include/torch/csrc/api/include -I /sps/l2it/collard/anaconda3/lib/python3.11/site-packages/torch/include $(python3.10-config --ldflags --embed)
